# Generated by Django 2.1.2 on 2018-10-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=128, unique=True)),
                ('diversity_type', models.CharField(max_length=128)),
                ('processus', models.CharField(max_length=128, unique=True)),
                ('planned_on', models.DateTimeField()),
                ('comment', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
