# Generated by Django 2.1.5 on 2019-01-23 13:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0002_auto_20190123_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(null=True)),
                ('values', django.contrib.postgres.fields.jsonb.JSONField()),
                ('current', models.BooleanField(default=False)),
                ('expected_after_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.Action')),
            ],
        ),
    ]
