# Generated by Django 2.1.5 on 2019-01-27 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('diversity_type', models.IntegerField(choices=[(1, 'Égalité Homme/Femme'), (2, 'Répartition Junior/Sénior'), (3, 'Représentation raciale'), (4, 'Accès aux personnes avec un handicap'), (5, 'Recrutement neutre'), (6, 'Promotions non discriminatoires'), (7, 'Télétravail'), (8, 'Commodités (crêches...)')])),
                ('processus', models.IntegerField(choices=[(1, 'Gestion des effectifs (entrées - sorties)'), (2, 'Intégration & culture'), (3, 'Formation'), (4, 'Evaluation'), (5, 'Promotion'), (6, 'Rémunération'), (7, 'Temps de travail'), (8, 'Communication'), (9, 'Participation'), (10, 'Relations professionnelles')])),
                ('planned_on', models.DateField()),
                ('comment', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Prévu'), (2, 'En cours'), (3, 'Fini')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
